# Disabled in fork – upstream release workflow
name: DISABLED – release job

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is disabled."
