# Disabled in fork – no HuggingFace deployment needed
name: DISABLED – deploy to HuggingFace Spaces

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is disabled."
