# Disabled: heavy upstream image build not needed in this fork
name: DISABLED – docker build upstream workflow

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is disabled in the fork."
