# Disabled in fork – frontend build formatting not needed
name: DISABLED – frontend build workflow

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is disabled."
